# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruise" do
  desc "Cruise is a powerful, intuitive, and fully-featured TUI (Terminal
User Interface) for interacting with Docker"
  homepage "https://nucleofusion.github.io/cruise/"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruise"

  on_macos do
    on_intel do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.1.0/cruise_Darwin_x86_64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "c9fe51b5f5b939d387d9e5e80619aca822ae97e625e17d94f75d1c300bd72f3e"
    end
    on_arm do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.1.0/cruise_Darwin_arm64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "8349f152ae9a74a8e35884a5825c5f4bf3cc0a8553862ceb82a89994a663e76d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.1.0/cruise_Linux_x86_64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "2fb14b0ca550d27b46b35acb3dd6c397320307d284ff59c53703d1bece9a1c86"
    end
    on_arm do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.1.0/cruise_Linux_arm64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "99495cca9267a553a39342dc75ac12c07db3efae866463579e2f168241dd3f17"
    end
  end

  # No zap stanza required
end
