# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruise" do
  desc "Cruise is a powerful, intuitive, and fully-featured TUI (Terminal
User Interface) for interacting with Docker"
  homepage "https://nucleofusion.github.io/cruise/"
  version "1.0.0-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruise"

  on_macos do
    on_intel do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0-rc.1/cruise_Darwin_x86_64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "1081553675954f8e61165a1bc6d8f33a02e1ea2906115a454c20751f5ff5b894"
    end
    on_arm do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0-rc.1/cruise_Darwin_arm64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "5266c3c8d4b6f2f5df3e777d29a0abd725a75b2f67f9f702e629461b784bfd52"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0-rc.1/cruise_Linux_x86_64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "81aa14fcd0a57b6121aa2cc526bc1966fdc627605adf6643ecabe22128edf5a6"
    end
    on_arm do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0-rc.1/cruise_Linux_arm64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "39922646369f39c2f6b4dbfb29e7f6d66b2526c7f76c8cf32ec4c0d669c4f37b"
    end
  end

  # No zap stanza required
end
