# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruise" do
  desc "Cruise is a powerful, intuitive, and fully-featured TUI (Terminal
User Interface) for interacting with Docker"
  homepage "https://nucleofusion.github.io/cruise/"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruise"

  on_macos do
    on_intel do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0/cruise_Darwin_x86_64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "987b893fcc2160303eb8397d95f09f619b52bee5119101b8681e6a3972e9d6e3"
    end
    on_arm do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0/cruise_Darwin_arm64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "cc453532be7e586d63bc5fed3f3b00ad8df058d331df7ded1b567972b379a81e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0/cruise_Linux_x86_64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "90294e4ca75c9ad0fab3998795ee8057be78c7a8288753a8d8f819783ca0f3ad"
    end
    on_arm do
      url "https://github.com/NucleoFusion/cruise/releases/download/v1.0.0/cruise_Linux_arm64.tar.gz",
        verified: "github.com/NucleoFusion/cruise"
      sha256 "2ea320cbe61cbd3a47e686115d385694bff02cd06c29fe2af718e8ea8bdfad6d"
    end
  end

  # No zap stanza required
end
